model_cfg:
  name: kobart
  pretrained_model_name_or_path: digit82/kobart-summarization
  encoder_max_len: 512
  decoder_max_len: 100
  bos_token: <s>
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#PhoneNumber#'
  - '#Address#'
  generate_max_length: 100
  num_beams: 4
  no_repeat_ngram_size: 2
  learning_rate: 1.0e-05
  weight_decay: 0.01
  warmup_ratio: 0.1
data_cfg:
  path: ./data/raw/
  batch_size: 16
