name: "flan-t5" # W&B에 표시될 이름

pretrained_model_name_or_path: "google/flan-t5-base"

# 나머지 설정은 pko-t5.yaml과 동일하게 유지
encoder_max_len: 128
decoder_max_len: 128
bos_token: "<s>" 
eos_token: "</s>"
special_tokens:
  - '<health_checkup>'
  - '<vaccination>'
  - '<lost_key>'
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  - '#PhoneNumber#'
  - '#Address#'
  
generate_max_length: 128
num_beams: 4
no_repeat_ngram_size: 2
learning_rate: 1.0e-05
weight_decay: 0.01
warmup_ratio: 0.1