name: "flan-t5" # W&B에 표시될 이름

pretrained_model_name_or_path: "google/flan-t5-base"

# 나머지 설정은 pko-t5.yaml과 동일하게 유지
encoder_max_len: 128
decoder_max_len: 128
bos_token: "<s>" 
eos_token: "</s>"
special_tokens:
  - '<health_checkup>'
  - '<vaccination>'
  - '<lost_key>'
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  - '#PhoneNumber#'
  - '#Address#'
  
# generate_max_length: 128
# num_beams: 4
# no_repeat_ngram_size: 2
# learning_rate: 1.0e-05
# weight_decay: 0.01
# warmup_ratio: 0.1


# 생성(추론) 관련 설정
generate_max_length: 128
num_beams: 4
no_repeat_ngram_size: 2

# 옵티마이저 및 스케줄러 설정 (최종 레시피)
learning_rate: 1.0e-4   # 표준적인 값으로 수정
weight_decay: 0.01
warmup_ratio: 0.1
label_smoothing: 0.1  # 라벨 스무딩 추가
lr_scheduler: "cosine_with_restarts" # 스케줄러 종류 명시