name: "pko-t5"
pretrained_model_name_or_path: "paust/pko-t5-base"
encoder_max_len: 512
decoder_max_len: 100
bos_token: "<s>"
eos_token: "</s>"
special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  - '#PhoneNumber#'
  - '#Address#'
generate_max_length: 100
num_beams: 4
no_repeat_ngram_size: 2
learning_rate: 1.0e-05
weight_decay: 0.01
warmup_ratio: 0.1