# @package _global_

# 기본값 설정
defaults:
  - data: default
  - model: kobart
  - trainer: default
  - _self_

# W&B 로거 설정
wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "team9-NLP"
  # 실행 이름에 학습률과 배치 사이즈를 추가하여 가독성 향상
  name: "${model.name}-lr_${model.learning_rate}-bs_${data.batch_size}"
  entity: null # wandb 계정 이름 (선택)
  log_model: "all" # "all"로 설정하면 모든 체크포인트를 wandb에 저장

# 일반 설정
seed: 42
