# configs/config.yaml
# @package _global_

# 기본값 설정
defaults:
  - data: default
  - model: kobart
  - trainer: default
  - _self_

# W&B 로거 설정
wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "nlp"
  # 실행 이름에 학습률과 배치 사이즈를 추가하여 가독성 향상
  name: "${model.name}-lr_${model.learning_rate}-bs_${data.batch_size}"
  entity: null # 
  # W&B 프로젝트는 특정 작업이나 실험을 나타내며, 엔티티는 해당 프로젝트를 소속하는 사용자나 팀을 나타냅니다.
  log_model: "all" # "all"로 설정하면 모든 체크포인트를 wandb에 저장

# 일반 설정
seed: 42


# 추론(Inference) 시 덮어쓸 생성(Generation) 관련 옵션
# 기본값은 null로 두어, 커맨드 라인에서 값을 주지 않으면 원래 모델 설정을 따르도록 함
generation:
  num_beams: null
  length_penalty: null
  repetition_penalty: null
  do_sample: null
  top_k: null
  top_p: null