model_cfg:
  name: flan-t5-large
  pretrained_model_name_or_path: google/flan-t5-large
  encoder_max_len: 256
  decoder_max_len: 128
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  generate_max_length: 128
  num_beams: 4
  no_repeat_ngram_size: 2
  learning_rate: 3.0e-05
  weight_decay: 0.01
  warmup_ratio: 0.1
  label_smoothing: 0.1
  lr_scheduler: cosine_with_restarts
